@JaReclamouHoje.Api_HostAddress = http://localhost:5001

GET {{JaReclamouHoje.Api_HostAddress}}/api/complaints
Accept: application/json

###

# @name createRequest
POST {{JaReclamouHoje.Api_HostAddress}}/api/complaints
Content-Type: application/json

{
  "title": "Elevator out of order",
  "description": "The east building elevator has been broken for two weeks."
}

###

# @name createRequest
POST {{JaReclamouHoje.Api_HostAddress}}/api/complaints
Content-Type: application/json

{
  "title": "T",
  "description": "Title is not lengthy enough."
}

###

GET {{JaReclamouHoje.Api_HostAddress}}/api/complaints/00000000-0000-0000-0000-000000000000
Accept: application/json