@JaReclamouHoje.Api_HostAddress = http://localhost:5001

GET {{JaReclamouHoje.Api_HostAddress}}/api/complaints
Accept: application/json

###

# @name createRequest
POST {{JaReclamouHoje.Api_HostAddress}}/api/complaints
Content-Type: application/json

{
  "title": "Elevator out of order",
  "description": "The east building elevator has been broken for two weeks."
}

###

GET {{JaReclamouHoje.Api_HostAddress}}/api/complaints/a2bb19c4-9900-4e15-883d-5cd96817062d
Accept: application/json